### ISSUE TITLE
Ability to convert to HSL

### ISSUE THREAD

**Issue by cvharris** [mikemcbride/convert-color-cli#1]
Could we add a flag like `-hsl` or `-to 'hsl` or `mode=hsl` that allows this tool to convert from rgb/hex to hsl?

This is, as of today, the most highly sought-after feature for this repo. I hope the maintainers take a look at this. 😉

**Comment by mikemcbride** [comment]
Hey, thanks for the interest in this project! I am definitely open to considering it, but I think it does open up a few issues to work through. I left HSL alone to start since HEX and RGB are the two more commonly used formats.

As far as the design, I think it would definitely have to be passed as a flag to avoid issues with parsing the input. Right now it concatenates the input strings and can parse them to RGB (say you pass in `255 255 255` without being wrapped in quotes).

```
convert-color [your color] --output hsl (or -o hsl)
```

Where the output defaults to HEX if it detects RGB, and vice versa, but you can also specify what you want it to be. So:

```
convert-color #ffffff -o hsl
```

Here are where my concerns with the implementation becoming too complex come into play. Not necessarily too complex to solve with code, but more in terms of UX. Right now the module is quite simple, and there's a level of elegance in that. It's very easy to pick up how it should be used and it behaves generally the way you'd expect, save a few quirks like requiring quotes if you pass in a HEX code with a leading `#`. Adding in a third format introduces a few complexities:

When I pass in a color format like this:

```
convert-color 150 25 65
```

it can tell right now that it's RGB. If we add HSL, it would be unable to tell whether that value should be parsed as RGB or HSL (since it's a valid array of numbers for both). That could certainly be solved by either assuming RGB in the cases where it's ambiguous (which could lead to unexpected outputs) or allowing another flag to be passed in to specify the input value, maybe something like:

```
convert-color 150 25 65 --input hsl --output rgb
```

However, now we are starting to encroach on the simplicity of the program and the options are getting more difficult to remember for me as a user of the module.

The other approach I see being a possible solution is disallowing the above format, and requiring that you specify rgb or hsl:

```
convert-color 'rgb(150, 25, 65)'
```

Again, that would solve the issue with ambiguous parsing but it does take away from the simplicity of the module.

Finally, we could simply start with something like only supporting HSL as an *output* format, and not an input. That may be a more reasonable approach.

I guess after thinking through all of this, I'm not really sure right now what I want to do about this right now. I'm certainly open to feedback on design implementations or other use cases. Thoughts?

**Comment by mikemcbride** [comment]
Okay so I’ve been thinking about this recently. I think if we made this a little more interactive using something like [Ink](https://github.com/vadimdemedes/ink) we could provide a more robust experience. It would allow us to still attempt to parse the argument if it’s passed in but if no arguments are passed we could prompt the user for input value and type and also output value and type. I think I’m going to take a stab at this when I get a little free time.
